
from django.urls import path
from server import views  # import from project folder
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('District/', views.District),
    path('DeleteDistrict/<int:did>/', views.DeleteDistrict),
    path('Admin/', views.Admin),
    path('DeleteAdmin/<int:aid>/', views.DeleteAdmin),
    path('City/', views.City),
    path('CityByDistrict/<int:district_id>/', views.CityByDistrict),
    path('DeleteCity/<int:cid>/', views.DeleteCity),
    path('Theater/', views.Theater),
    path('DeleteTheater/<int:tid>/', views.DeleteTheater),
    path('User/', views.User),
    path('DeleteUser/<int:uid>/', views.DeleteUser),
    path('Booking/', views.Booking),
    path('DeleteBooking/<int:bid>/', views.DeleteBooking),
    path('Genre/', views.Genre),
    path('DeleteGenre/<int:gid>/', views.DeleteGenre),
    path('EditGenre/<int:gid>/', views.EditGenre),
    path('Trailer/', views.Trailer),
    path('DeleteTrailer/<int:trid>/', views.DeleteTrailer),
    path('Review/', views.Review),
    path('DeleteReview/<int:rid>/', views.DeleteReview),
    path('Screentype/', views.Screentype),
    path('DeleteScreentype/<int:stid>/', views.DeleteScreentype),
    path('EditScreentype/<int:stid>/', views.EditScreentype),
    path('Complaint/', views.Complaint),
    path('DeleteComplaint/<int:cid>/', views.DeleteComplaint),
    path('TheaterMovie/', views.Theatermovie),
    path('DeleteTheatermovie/<int:tmid>/', views.DeleteTheatermovie),
    path('Movie/', views.Movie),
    path('DeleteMovie/<int:mid>/', views.DeleteMovie),
    path('Screen/', views.Screen),
    path('DeleteScreen/<int:sid>/', views.DeleteScreen),
    path('Shows/', views.Shows),
    path('DeleteShows/<int:shid>/', views.DeleteShows),
    path('ScreenSeat/', views.ScreenSeat),
    path('DeleteScreenSeat/<int:ssid>/', views.DeleteScreenSeat),
    path('SeatBooking/', views.SeatBooking),
    path('DeleteSeatBooking/',views.DeleteSeatBooking),
    path('EditSeatType/<int:stid>/', views.EditSeatType),
    path('Feedback/', views.Feedback),
    path('DeleteFeedback/<int:fid>/', views.DeleteFeedback),
    path('SeatType/', views.SeatType),
    path('DeleteSeatType/<int:stid>/', views.DeleteSeatType),   
    path('theaterprofile/<int:id>/', views.theaterprofile),   
    path('edittheaterprofile/<int:id>/', views.theatereditprofile),
    path('changepassword/<int:id>/', views.changepassword),
    path('Screentype/', views.Screentype),
    path('DeleteScreentype/<int:stid>/', views.DeleteScreentype),
    path('EditScreentype/<int:stid>/', views.EditScreentype),
    path('Login/', views.Login),
    path('Movie/<int:mid>/', views.MovieDetails),
    path('UserProfile/<int:id>/', views.userprofile),
    path('EditUserProfile/<int:id>/', views.usereditprofile),
    path('ChangeUserPassword/<int:id>/', views.userchangepassword),
    path('MovieTheatersWithShows/<int:mid>/', views.MovieTheatersWithShows),
    path('viewseat/<int:sid>/', views.viewseat),
    path("BookedSeats/<int:screen_id>/", views.BookedSeats),
    path('make-payment/<int:booking_id>/', views.make_payment),
    path('booking-details/<int:booking_id>/', views.booking_details),
    path('MyBookings/<int:user_id>/', views.MyBookings),
path("bookedSeats/<int:screen_id>/<int:movie_id>/<str:show_time>/", views.BookedSeatsForShow),]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)