# Generated by Django 6.0 on 2025-12-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_tbl_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=30)),
                ('admin_email', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_type',
        ),
    ]
