# Generated by Django 6.0 on 2026-01-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_tbl_admin_delete_tbl_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
            ],
        ),
    ]
