# Generated by Django 6.0 on 2026-01-06 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('booking_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('booking_time', models.TimeField()),
                ('booking_date', models.DateField()),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_city',
            fields=[
                ('city_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_district')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('complaint_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('complaint_title', models.CharField(max_length=100)),
                ('complaint_content', models.TextField()),
                ('complaint_reply', models.TextField(blank=True)),
                ('complaint_status', models.CharField(max_length=20)),
                ('complaint_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_genre',
            fields=[
                ('genre_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_movie',
            fields=[
                ('movie_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_description', models.TextField()),
                ('movie_duration', models.CharField(max_length=10)),
                ('movie_language', models.CharField(max_length=30)),
                ('movie_poster', models.CharField(max_length=100)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_genre')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('review_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('review_content', models.TextField()),
                ('review_datetime', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_movie')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_screen',
            fields=[
                ('screen_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('screen_seatno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_screentype',
            fields=[
                ('screentype_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('screentype_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_shows',
            fields=[
                ('shows_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_movie')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_theater',
            fields=[
                ('theater_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('theater_name', models.CharField(max_length=50)),
                ('theater_email', models.EmailField(max_length=50)),
                ('theater_contact', models.CharField(max_length=15)),
                ('theater_photo', models.CharField(max_length=100)),
                ('theater_proof', models.CharField(max_length=100)),
                ('theater_status', models.CharField(max_length=20)),
                ('theater_password', models.CharField(max_length=128)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_city')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_theatermovie',
            fields=[
                ('theatermovie_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_theater')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_trailer',
            fields=[
                ('trailer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('trailer_file', models.CharField(max_length=100)),
                ('trailer_description', models.CharField(max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_movie')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_contact', models.CharField(max_length=15)),
                ('user_password', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
        migrations.AlterField(
            model_name='tbl_admin',
            name='admin_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_admin',
            name='admin_password',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_movie'),
        ),
        migrations.AddField(
            model_name='tbl_screen',
            name='screentype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screentype'),
        ),
        migrations.AddField(
            model_name='tbl_shows',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screen'),
        ),
        migrations.AddField(
            model_name='tbl_screen',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_theater'),
        ),
        migrations.AddField(
            model_name='tbl_review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user'),
        ),
        migrations.AddField(
            model_name='tbl_complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user'),
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user'),
        ),
    ]
