# Generated by Django 6.0 on 2026-01-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_tbl_booking_tbl_city_tbl_complaint_tbl_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='tbl_city',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='complaint_id',
        ),
        migrations.RemoveField(
            model_name='tbl_genre',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='tbl_movie',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='tbl_review',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='tbl_screen',
            name='screen_id',
        ),
        migrations.RemoveField(
            model_name='tbl_screentype',
            name='screentype_id',
        ),
        migrations.RemoveField(
            model_name='tbl_shows',
            name='shows_id',
        ),
        migrations.RemoveField(
            model_name='tbl_theater',
            name='theater_id',
        ),
        migrations.RemoveField(
            model_name='tbl_theatermovie',
            name='theatermovie_id',
        ),
        migrations.RemoveField(
            model_name='tbl_trailer',
            name='trailer_id',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tbl_city',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tbl_complaint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tbl_genre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tbl_movie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tbl_review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tbl_screen',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tbl_screentype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tbl_shows',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tbl_theater',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tbl_theatermovie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tbl_trailer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
