# Generated by Django 6.0 on 2026-01-06 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_remove_tbl_booking_booking_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_booking',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='tbl_booking',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='tbl_city',
            old_name='district',
            new_name='district_id',
        ),
        migrations.RenameField(
            model_name='tbl_movie',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='tbl_review',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='tbl_review',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='tbl_screen',
            old_name='screentype',
            new_name='screentype_id',
        ),
        migrations.RenameField(
            model_name='tbl_screen',
            old_name='theater',
            new_name='theater_id',
        ),
        migrations.RenameField(
            model_name='tbl_shows',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='tbl_shows',
            old_name='screen',
            new_name='screen_id',
        ),
        migrations.RenameField(
            model_name='tbl_theater',
            old_name='city',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='tbl_theatermovie',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='tbl_theatermovie',
            old_name='theater',
            new_name='theater_id',
        ),
        migrations.RenameField(
            model_name='tbl_trailer',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.TextField()),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_screenseat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenseat_total', models.CharField(max_length=10)),
                ('screenseat_amountper', models.CharField(max_length=10)),
                ('screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screen')),
                ('screentype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screentype')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_seatbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatbooking_number', models.CharField(max_length=10)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_booking')),
                ('screenseat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screenseat')),
            ],
        ),
    ]
