# Generated by Django 6.0 on 2026-01-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_rename_movie_tbl_booking_movie_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_complaint',
            old_name='user',
            new_name='user_id',
        ),
    ]
