# Generated by Django 6.0 on 2026-01-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_rename_user_tbl_complaint_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_contact',
        ),
    ]
