# Generated by Django 6.0 on 2026-01-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_remove_tbl_user_user_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='booking_status',
        ),
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='complaint_status',
        ),
        migrations.RemoveField(
            model_name='tbl_theater',
            name='theater_status',
        ),
        migrations.AlterField(
            model_name='tbl_movie',
            name='movie_poster',
            field=models.FileField(upload_to='Assets/UserPhoto/'),
        ),
        migrations.AlterField(
            model_name='tbl_theater',
            name='theater_photo',
            field=models.FileField(upload_to='Assets/UserPhoto/'),
        ),
        migrations.AlterField(
            model_name='tbl_theater',
            name='theater_proof',
            field=models.FileField(upload_to='Assets/UserPhoto/'),
        ),
        migrations.AlterField(
            model_name='tbl_trailer',
            name='trailer_file',
            field=models.FileField(upload_to='Assets/UserPhoto/'),
        ),
    ]
