# Generated by Django 6.0 on 2026-01-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_remove_tbl_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_movie',
            name='genre_id',
        ),
    ]
