# Generated by Django 6.0 on 2026-01-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_alter_tbl_booking_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_seatbooking',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='tbl_seatbooking',
            name='screenseat_id',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_seatbooking',
        ),
    ]
