# Generated by Django 6.0 on 2026-01-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_tbl_booking_tbl_seatbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='booking_time',
        ),
        migrations.RemoveField(
            model_name='tbl_booking',
            name='booking_todate',
        ),
    ]
