# Generated by Django 6.0 on 2026-01-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_tbl_booking_tbl_seatbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
