# Generated by Django 6.0 on 2026-01-06 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_delete_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=100)),
                ('complaint_content', models.TextField()),
                ('complaint_reply', models.TextField(blank=True)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('theater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_theater')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
    ]
