# Generated by Django 6.0 on 2026-01-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_seattype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seattype_name', models.CharField(max_length=50)),
            ],
        ),
    ]
