# Generated by Django 6.0 on 2026-02-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_seatbooking',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='tbl_review',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='tbl_shows',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='tbl_theatermovie',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='tbl_trailer',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='tbl_review',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_seatbooking',
            name='screenseat_id',
        ),
        migrations.RemoveField(
            model_name='tbl_shows',
            name='screen_id',
        ),
        migrations.RemoveField(
            model_name='tbl_theatermovie',
            name='theater_id',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_movie',
        ),
        migrations.DeleteModel(
            name='tbl_trailer',
        ),
        migrations.DeleteModel(
            name='tbl_review',
        ),
        migrations.DeleteModel(
            name='tbl_seatbooking',
        ),
        migrations.DeleteModel(
            name='tbl_shows',
        ),
        migrations.DeleteModel(
            name='tbl_theatermovie',
        ),
    ]
