# Generated by Django 6.0 on 2026-02-17 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0024_remove_tbl_seatbooking_booking_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_description', models.TextField()),
                ('movie_duration', models.CharField(max_length=10)),
                ('movie_language', models.CharField(max_length=30)),
                ('movie_poster', models.FileField(upload_to='Assets/UserPhoto/')),
                ('movie_banner', models.FileField(null=True, upload_to='Assets/UserPhoto/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.TimeField()),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_todate', models.DateField()),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_movie')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField()),
                ('review_datetime', models.DateTimeField(auto_now_add=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_seatbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatbooking_number', models.CharField(max_length=10)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_booking')),
                ('screenseat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screenseat')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_movie')),
                ('screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screen')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_theatermovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_movie')),
                ('theater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_theater')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_file', models.FileField(upload_to='Assets/UserPhoto/')),
                ('trailer_description', models.CharField(max_length=200)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_movie')),
            ],
        ),
    ]
