# Generated by Django 6.0 on 2026-02-18 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0026_delete_tbl_admin_remove_tbl_booking_movie_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=30)),
                ('admin_email', models.EmailField(max_length=50)),
                ('admin_password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_description', models.TextField()),
                ('movie_duration', models.CharField(max_length=10)),
                ('movie_language', models.CharField(max_length=30)),
                ('movie_poster', models.FileField(upload_to='Assets/Movies/')),
                ('movie_banner', models.FileField(upload_to='Assets/Movies/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_seatno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_screentype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screentype_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_seattype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seattype_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_password', models.CharField(max_length=128)),
                ('user_contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_district')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.TimeField()),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_todate', models.DateField()),
                ('booking_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_screenseat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenseat_total', models.CharField(max_length=10)),
                ('screenseat_amountper', models.CharField(max_length=10)),
                ('screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screen')),
                ('screentype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screentype')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_screen',
            name='screentype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screentype'),
        ),
        migrations.CreateModel(
            name='tbl_seatbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatbooking_number', models.CharField(max_length=10)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_booking')),
                ('screenseat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screenseat')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_movie')),
                ('screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screen')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=50)),
                ('theater_email', models.EmailField(max_length=50)),
                ('theater_contact', models.CharField(max_length=15)),
                ('theater_photo', models.FileField(upload_to='Assets/TheaterPhoto/')),
                ('theater_proof', models.FileField(upload_to='Assets/TheaterProof/')),
                ('theater_password', models.CharField(max_length=128)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_city')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_screen',
            name='theater_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_theater'),
        ),
        migrations.CreateModel(
            name='tbl_theatermovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_movie')),
                ('theater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_theater')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_file', models.FileField(upload_to='Assets/Movies/')),
                ('trailer_description', models.CharField(max_length=200)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_movie')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.TextField()),
                ('review_datetime', models.DateTimeField(auto_now_add=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.TextField()),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=100)),
                ('complaint_content', models.TextField()),
                ('complaint_reply', models.TextField(blank=True)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('theater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_theater')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
    ]
