# Generated by Django 6.0 on 2026-02-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_shows',
        ),
    ]
