# Generated by Django 6.0 on 2026-02-23 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0029_tbl_shows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_shows',
            name='screen_id',
        ),
        migrations.RemoveField(
            model_name='tbl_screenseat',
            name='screen_id',
        ),
        migrations.RemoveField(
            model_name='tbl_screenseat',
            name='screentype_id',
        ),
        migrations.RemoveField(
            model_name='tbl_seatbooking',
            name='screenseat_id',
        ),
        migrations.RemoveField(
            model_name='tbl_seatbooking',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='tbl_shows',
            name='movie_id',
        ),
        migrations.DeleteModel(
            name='tbl_screen',
        ),
        migrations.DeleteModel(
            name='tbl_screenseat',
        ),
        migrations.DeleteModel(
            name='tbl_seatbooking',
        ),
        migrations.DeleteModel(
            name='tbl_shows',
        ),
    ]
