# Generated by Django 6.0 on 2026-02-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0031_tbl_screen_tbl_screenseat_tbl_seatbooking_tbl_shows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_seatbooking',
            name='screenseat_id',
        ),
        migrations.RemoveField(
            model_name='tbl_seatbooking',
            name='booking_id',
        ),
        migrations.DeleteModel(
            name='tbl_screenseat',
        ),
        migrations.DeleteModel(
            name='tbl_seatbooking',
        ),
    ]
