# Generated by Django 6.0 on 2026-02-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0032_remove_tbl_seatbooking_screenseat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_screen',
            name='screentype_id',
        ),
        migrations.RemoveField(
            model_name='tbl_screen',
            name='theater_id',
        ),
        migrations.RemoveField(
            model_name='tbl_shows',
            name='screen_id',
        ),
        migrations.DeleteModel(
            name='tbl_seattype',
        ),
        migrations.RemoveField(
            model_name='tbl_shows',
            name='movie_id',
        ),
        migrations.DeleteModel(
            name='tbl_screentype',
        ),
        migrations.DeleteModel(
            name='tbl_screen',
        ),
        migrations.DeleteModel(
            name='tbl_shows',
        ),
    ]
