# Generated by Django 6.0 on 2026-02-23 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0033_remove_tbl_screen_screentype_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_screentype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screentype_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_seattype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seattype_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_seatno', models.CharField(max_length=50)),
                ('Screen_name', models.CharField(max_length=50)),
                ('theater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_theater')),
                ('screentype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screentype')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_screenseat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenseat_total', models.CharField(max_length=10)),
                ('screenseat_amountper', models.CharField(max_length=10)),
                ('screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screen')),
                ('seattype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_seattype')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_seatbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatbooking_number', models.CharField(max_length=10)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_booking')),
                ('screenseat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screenseat')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.TimeField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_movie')),
                ('screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screen')),
            ],
        ),
    ]
