# Generated by Django 6.0 on 2026-02-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0034_tbl_screentype_tbl_seattype_tbl_screen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_seatbooking',
            name='screenseat_id',
        ),
        migrations.RemoveField(
            model_name='tbl_seatbooking',
            name='booking_id',
        ),
        migrations.DeleteModel(
            name='tbl_screenseat',
        ),
        migrations.DeleteModel(
            name='tbl_seatbooking',
        ),
    ]
