# Generated by Django 6.0 on 2026-02-27 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0035_remove_tbl_seatbooking_screenseat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_screenseat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.IntegerField()),
                ('columns', models.IntegerField()),
                ('aisles', models.CharField(blank=True, max_length=100, null=True)),
                ('screenseat_total', models.IntegerField()),
                ('screenseat_amountper', models.IntegerField()),
                ('screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screen')),
                ('seattype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_seattype')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_seatbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatbooking_number', models.CharField(max_length=10)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_booking')),
                ('screenseat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_screenseat')),
            ],
        ),
    ]
