# Generated by Django 6.0 on 2026-03-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0036_tbl_screenseat_tbl_seatbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='booking_status',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
