# Generated by Django 6.0 on 2026-03-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0037_tbl_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_status',
            field=models.IntegerField(default=0),
        ),
    ]
